runtime: python27
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  script: main.app
  secure: always

- url: /.*
  script: main.app
  secure: always


libraries:
- name: webapp2
  version: latest